/*
 -------------------------------------------------------------------------------
    This file is part of thermos.
    Copyright (C) 2022  Dirk Stolle

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 -------------------------------------------------------------------------------
*/

#ifndef THERMOS_TEMPLATING_TEMPLATE_HPP
#define THERMOS_TEMPLATING_TEMPLATE_HPP

#include <filesystem>
#include <optional>
#include <string>
#include <unordered_map>

namespace thermos
{

class Template
{
  public:
    static const std::string TAG_OPENER;
    static const std::string TAG_CLOSER;
    static const std::string INTEGRATE_OPENER;
    static const std::string INTEGRATE_CLOSER;


    Template();

    /**
     * Loads template from a file.
     *
     * @param file_name  path to the template file
     * @return Returns true, if template was loaded successfully.
     *         Returns false otherwise.
     */
    bool load_from_file(const std::filesystem::path& file_name);


    /**
     * Loads template from a string.
     *
     * @param content  content of the template
     * @return Returns true, if template was loaded successfully.
     *         Returns false otherwise.
     */
    bool load_from_str(const std::string& content);


    /**
     * Loads a section of the template.
     *
     * @param section_name  name of the section to load
     * @return true if section was loaded, false otherwise
     */
    bool load_section(const std::string& section_name);


    /**
     * Sets the replacements text for a tag.
     * HTML entities in replacement are escaped during template generation.
     * Therefore it can also be used to show raw user input safely.
     *
     * @param name  name of the tag to replace
     * @param replacement the replacement
     */
    void tag(const std::string& name, const std::string& replacement);


    /**
     * Sets the replacements text for an included template.
     * HTML entities in replacement are NOT escaped during template generation.
     * Therefore integrate() is suitable to include stuff generated by other
     * templates, since any HTML is preserved. However, it is NOT suitable to
     * include raw user input.
     *
     * @param name  name of the template to include
     * @param replacement the replacement
     */
    void integrate(const std::string& name, const std::string& replacement);

    /**
     * Generates the final template, ready for display.
     *
     * @return the template with all replacement values filled
     */
    std::optional<std::string> generate() const;


    std::unordered_map<std::string, std::string> sections;
    std::unordered_map<std::string, std::string> tags;
    std::unordered_map<std::string, std::string> includes;
    std::optional<std::string> tpl;
};

} // namespace

#endif // THERMOS_TEMPLATING_TEMPLATE_HPP
