name: GCC

on: push

jobs:
  ubuntu_20_04_gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [8, 9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-${{ matrix.version }} libsqlite3-dev pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build with GNU GCC ${{ matrix.version }} - no SQLite
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-no-sqlite
          cd build-no-sqlite
          cmake ../ -DNO_SQLITE=ON
          make -j4
      - name: Tests - no SQLite
        run: |
          cd "$GITHUB_WORKSPACE"/build-no-sqlite
          ctest -V
