name: MSVC

on: push

jobs:
  windows_msvc:
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Build with Visual Studio ${{ matrix.version }} - no SQLite
        run: |
          cd "%GITHUB_WORKSPACE%"
          md build-no-sqlite
          cd build-no-sqlite
          cmake .. -DNO_SQLITE=ON
          cmake --build .
        shell: cmd
      - name: Tests - no SQLite
        run: |
          cd "%GITHUB_WORKSPACE%\build-no-sqlite"
          ctest -C Debug -V
        shell: cmd
