name: MSVC

on: push

jobs:
  windows_msvc:
    strategy:
      matrix:
        version: [2022, 2025]
    runs-on: windows-${{ matrix.version }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Build with Visual Studio ${{ matrix.version }} - no SQLite
        run: |
          cd "%GITHUB_WORKSPACE%"
          md build-no-sqlite
          cd build-no-sqlite
          cmake .. -DNO_SQLITE=ON
          cmake --build .
        shell: cmd
      - name: Tests - no SQLite
        run: |
          cd "%GITHUB_WORKSPACE%\build-no-sqlite"
          ctest -C Debug -V
        shell: cmd
      - name: Build with Visual Studio ${{ matrix.version }} - bundled SQLite
        run: |
          cd "%GITHUB_WORKSPACE%"
          md build-bundled
          cd build-bundled
          cmake .. -DUSE_BUNDLED_SQLITE=ON -DENABLE_LTO=ON
          cmake --build .
        shell: cmd
      - name: Tests - bundled SQLite
        run: |
          cd "%GITHUB_WORKSPACE%\build-bundled"
          ctest -C Debug -V
        shell: cmd
